In [1]:
import pandas as pd
import numpy as np
from scipy.spatial import distance

In [2]:
s1 = np.array([(0,0), (0,1), (1,0), (1,1)])
s2 = np.array([(3,2), (1,9)])
print(distance.cdist(s1,s2).min(axis=1))


[3.60555128 3.16227766 2.82842712 2.23606798]


In [46]:
s1

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [4]:
df= pd.read_csv("MRT Stations.csv")

In [6]:
df.head()

Unnamed: 0  OBJECTID                    STN_NAME STN_NO  \
0           0         1           EUNOS MRT STATION    EW7   
1           1         2  CHINESE GARDEN MRT STATION   EW25   
2           2         3          KHATIB MRT STATION   NS14   
3           3         4          KRANJI MRT STATION    NS7   
4           4         5         REDHILL MRT STATION   EW18   

                                      geometry  Latitude   Longitude  
0  POINT (103.9032524667383 1.319778951553637)  1.319779  103.903252  
1  POINT (103.7325967380734 1.342352820874744)  1.342353  103.732597  
2  POINT (103.8329799077383 1.417383370153547)  1.417383  103.832980  
3  POINT (103.7621654109002 1.425177698770448)  1.425178  103.762165  
4   POINT (103.816816670149 1.289562726402453)  1.289563  103.816817

In [56]:
#df['Coordinates'] = ( + df['Longitude'].astype(str)+","+df['Latitude'].astype(str) + )
df['Coordinates'] = list(zip(df.Longitude, df.Latitude))

In [57]:
df.head()

Unnamed: 0  OBJECTID                    STN_NAME STN_NO  \
0           0         1           EUNOS MRT STATION    EW7   
1           1         2  CHINESE GARDEN MRT STATION   EW25   
2           2         3          KHATIB MRT STATION   NS14   
3           3         4          KRANJI MRT STATION    NS7   
4           4         5         REDHILL MRT STATION   EW18   

                                      geometry  Latitude   Longitude  \
0  POINT (103.9032524667383 1.319778951553637)  1.319779  103.903252   
1  POINT (103.7325967380734 1.342352820874744)  1.342353  103.732597   
2  POINT (103.8329799077383 1.417383370153547)  1.417383  103.832980   
3  POINT (103.7621654109002 1.425177698770448)  1.425178  103.762165   
4   POINT (103.816816670149 1.289562726402453)  1.289563  103.816817   

                                Coordinates  
0  (103.90325246673828, 1.3197789515536371)  
1  (103.73259673807335, 1.3423528208747444)  
2  (103.83297990773832, 1.4173833701535468)  
3   (103.7621654109002, 1.4251776987704483)  
4  (103.81681667014902, 1.2895627264024532)

In [66]:
mrt_coordinates=df["Coordinates"].to_list()

In [67]:
mrt_coordinates

[(103.90325246673828, 1.3197789515536371),
 (103.73259673807335, 1.3423528208747444),
 (103.83297990773832, 1.4173833701535468),
 (103.7621654109002, 1.4251776987704483),
 (103.81681667014902, 1.2895627264024532),
 (103.74740511413792, 1.3975350177934125),
 (103.69732151293609, 1.3375868822047494),
 (103.79830451562896, 1.3024387353271702),
 (103.8930603552516, 1.318112082295278),
 (103.95337169417571, 1.343202894930727),
 (103.945148688649, 1.3533013563424343),
 (103.80098800081232, 1.4405850010854109),
 (103.8350050461946, 1.4294430808108003),
 (103.9492681182454, 1.37298377357949),
 (103.76529887432638, 1.3149544924235943),
 (103.88290604466044, 1.316432611657838),
 (103.84993299388984, 1.3693473037885635),
 (103.96154821070796, 1.3345497778378117),
 (103.74434094618154, 1.3853616928288095),
 (103.7422865440047, 1.3331526198940653),
 (103.805884333892, 1.2948609327949876),
 (103.63687867834884, 1.340463765648207),
 (103.660552955908, 1.3195052149382065),
 (103.78648513490744, 1.4368

In [68]:
mrt_stations_np=np.array(mrt_coordinates)

In [31]:
type(mrt_stations_np)

numpy.ndarray

In [35]:
df1=pd.read_csv("HDB_resales_coordinates.csv")

In [36]:
df1.head()

Latitude   Longitude                           Coordinate
0  1.362005  103.853880  (1.36200453938712,103.853879910407)
1  1.370966  103.838202  (1.37096635222625,103.838201940326)
2  1.380709  103.835368  (1.38070883044887,103.835368226602)
3  1.366201  103.857201   (1.3662010408294,103.857200967235)
4  1.381041  103.835132  (1.38104135523576,103.835131742647)

In [73]:
#df1['Coordinates'] =  df1['Longitude'].astype(str)+","+df1['Latitude'].astype(str)
df1['Coordinates'] = list(zip(df1.Longitude, df1.Latitude))

In [74]:
df1.head()

Latitude   Longitude                           Coordinate  \
0  1.362005  103.853880  (1.36200453938712,103.853879910407)   
1  1.370966  103.838202  (1.37096635222625,103.838201940326)   
2  1.380709  103.835368  (1.38070883044887,103.835368226602)   
3  1.366201  103.857201   (1.3662010408294,103.857200967235)   
4  1.381041  103.835132  (1.38104135523576,103.835131742647)   

                  Coordinates  
0  (103.8538799, 1.362004539)  
1  (103.8382019, 1.370966352)  
2   (103.8353682, 1.38070883)  
3   (103.857201, 1.366201041)  
4  (103.8351317, 1.381041355)

In [75]:
HDB_coordinates=df1["Coordinates"].to_list()
HDB_coordinates

[(103.8538799, 1.362004539),
 (103.8382019, 1.370966352),
 (103.8353682, 1.38070883),
 (103.857201, 1.366201041),
 (103.8351317, 1.381041355),
 (103.842018, 1.376806785),
 (103.855898, 1.367503711),
 (103.8417425, 1.365119086),
 (103.855898, 1.367503711),
 (103.8548806, 1.370055013),
 (103.8541682, 1.374058463),
 (103.8367406, 1.36754925),
 (103.8364912, 1.366823609),
 (103.840654, 1.36598198),
 (103.8541005, 1.374473785),
 (103.8378964, 1.368854452),
 (103.8560231, 1.369743586),
 (103.8400023, 1.381561712),
 (103.8541683, 1.366050278),
 (103.8412115, 1.382198677),
 (103.8446989, 1.369563443),
 (103.8346302, 1.370654871),
 (103.8536003, 1.36830997),
 (103.8416666, 1.369196966),
 (103.8534978, 1.37071308),
 (103.8354757, 1.373295936),
 (103.8516986, 1.361342556),
 (103.8359677, 1.370615176),
 (103.8510307, 1.362431864),
 (103.8577361, 1.371625702),
 (103.8456602, 1.367089832),
 (103.8559533, 1.371388551),
 (103.8501398, 1.374000865),
 (103.8581186, 1.363143927),
 (103.8565159, 1.3626629

In [77]:
HDB_np=np.array(HDB_coordinates)
HDB_np

array([[103.8538799 ,   1.36200454],
       [103.8382019 ,   1.37096635],
       [103.8353682 ,   1.38070883],
       ...,
       [103.8448431 ,   1.42540417],
       [103.8448431 ,   1.42540417],
       [103.837437  ,   1.42133516]])

In [80]:
distances=distance.cdist(HDB_coordinates,mrt_stations_np).min(axis=1)

In [82]:
distances.tolist()

[0.008336321885734434,
 0.0017759048399419491,
 0.004490262780872086,
 0.007919777923156401,
 0.004237314393043877,
 0.005751167188409613,
 0.006243407103840107,
 0.00852872213713084,
 0.006243407103840107,
 0.004997965440985693,
 0.006334981603058946,
 0.004538153832283251,
 0.004999856373940805,
 0.00720668289155781,
 0.0066067326863940255,
 0.003405468877569266,
 0.006102985500897491,
 0.004948806868035581,
 0.005367326792474873,
 0.00376192067832969,
 0.00523855466769004,
 0.002619621886032904,
 0.0038111934475317227,
 0.0056392944043121545,
 0.0038174844155252218,
 0.001811112803777848,
 0.008197155122039406,
 0.001702449900820636,
 0.00700201872130655,
 0.008128933717055996,
 0.0048324886447057135,
 0.006356947053280654,
 0.004658154217690101,
 0.010270639267912322,
 0.009381623745543454,
 0.004829689718461475,
 0.00829341314397497,
 0.005090370099645116,
 0.002847792911662541,
 0.008565558010786343,
 0.004237314393043877,
 0.007543111721695757,
 0.007914261266891834,
 0.00580988

In [85]:
dict={'distances':distances}
df2=pd.DataFrame(dict)
df2.to_csv("Distances.csv")